apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1238938487-deployment
  labels:
    app: dgc-1238938487
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dgc-1238938487
  template:
    metadata:
      labels:
        app: dgc-1238938487
    spec:
      containers:
      - name: mi-contenedor
        image: 047719650114.dkr.ecr.us-east-1.amazonaws.com/d1238938487:latest
        ports:
        - containerPort: 80
